spring.application.name=animeoldies

spring.datasource.url=jdbc:postgresql://db.soukolfgdapjkfrwlxrk.supabase.co:5432/postgres?sslmode=require
#jdbc:mysql://localhost:3306/animeoldies
spring.datasource.username=postgres
spring.datasource.password=cAv8RhmXGaCwnHxZ
#cAv8RhmXGaCwnHxZ

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-dll=true